
tasks:
  - command: python -m http.server
  - command: |
      sudo apt-get update
      sudo apt-get install haxe -y
      mkdir ~/haxelib && haxelib setup ~/haxelib
      yes | haxelib install game.hxml
      watch -x bash -c 'haxe game.hxml |& tail -n4'
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-browser
  - port: 6000 # Haxe compiler

    onOpen: ignore
vscode:
  extensions:
    - nadako.vshaxe