# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt-get install haxe -y
      mkdir ~/haxelib && haxelib setup ~/haxelib
      yes | haxelib install game.hxml
      haxe game.hxml
    command: python -m http.server
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
