#!/bin/bash
# Inspired by https://james-forbes.com/?/posts/alternative-to-npm-scripts#!/posts/alternative-to-npm-scripts

set -e

function buildres() {
    haxe -python build/pak.py -lib heaps -main hxd.fmt.pak.Build
    python3 build/pak.py -res res/heaps -out public/build/res
}

if [[ $# -eq 0 ]] ; then
    echo "Available sub-commands:"
    declare -F | awk '{print "- "$NF}' | sort | egrep -v "^_" 
    exit
fi

# Run a function name in the context of this script
eval "$@"